"""initial schema

Revision ID: 0768c92cbf73
Revises: 
Create Date: 2026-08-20 14:27:43.400594

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0768c92cbf73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'TESTED', 'SCHEDULED', 'SENDING', 'SENT', 'PARTIAL', 'FAILED', name='campaignstatus', native_enum=False, length=16), server_default='DRAFT', nullable=False),
    sa.Column('clear_polish', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('test_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_status'), ['status'], unique=False)

    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acronym', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('nip', sa.String(length=16), nullable=True),
    sa.Column('nip_valid', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('city', sa.String(length=160), nullable=True),
    sa.Column('postal_code', sa.String(length=16), nullable=True),
    sa.Column('street', sa.String(length=300), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('source', sa.Enum('IMPORT', 'MANUAL', 'TRANSCRIPT', name='clientsource', native_enum=False, length=16), server_default='MANUAL', nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'BLACKLIST', name='clientstatus', native_enum=False, length=16), server_default='ACTIVE', nullable=False),
    sa.Column('sms_consent', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sms_consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_acronym'), ['acronym'], unique=True)
        batch_op.create_index(batch_op.f('ix_clients_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_name'), ['name'], unique=False)
        batch_op.create_index('ix_clients_name_city', ['name', 'city'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_nip'), ['nip'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_status'), ['status'], unique=False)

    op.create_table('import_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'DONE', 'FAILED', name='importstatus', native_enum=False, length=16), server_default='PENDING', nullable=False),
    sa.Column('total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('processed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated', sa.Integer(), server_default='0', nullable=False),
    sa.Column('skipped', sa.Integer(), server_default='0', nullable=False),
    sa.Column('flagged', sa.Integer(), server_default='0', nullable=False),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_jobs_status'), ['status'], unique=False)

    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('CLIENT_CREATED', 'CLIENT_UPDATED', 'NOTE_ADDED', 'SMS_SENT', 'SMS_DELIVERED', 'SMS_FAILED', 'CALL_TRANSCRIBED', 'EVENT_SCHEDULED', 'TAG_ADDED', 'TAG_REMOVED', 'MANUAL', name='activitytype', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actor', sa.Enum('USER', 'SYSTEM', 'AI', name='activityactor', native_enum=False, length=16), server_default='USER', nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index('ix_activities_client_occurred', ['client_id', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_type'), ['type'], unique=False)

    op.create_table('campaign_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.String(length=64), nullable=True),
    sa.Column('buffered', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('recipient_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'CANCELLED', name='batchstatus', native_enum=False, length=16), server_default='PENDING', nullable=False),
    sa.Column('error_code', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_batches_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_batches_provider_id'), ['provider_id'], unique=False)

    op.create_table('campaign_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('phone_e164', sa.String(length=20), nullable=False),
    sa.Column('rendered_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'DELIVERED', 'FAILED', 'SKIPPED', name='recipientstatus', native_enum=False, length=16), server_default='PENDING', nullable=False),
    sa.Column('parts', sa.Integer(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_error', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_recipients', schema=None) as batch_op:
        batch_op.create_index('ix_campaign_recipients_campaign_status', ['campaign_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_recipients_phone_e164'), ['phone_e164'], unique=False)

    op.create_table('client_tags',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('client_id', 'tag_id')
    )
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('pinned', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index('ix_notes_client_created', ['client_id', 'created_at'], unique=False)

    op.create_table('phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('e164', sa.String(length=20), nullable=True),
    sa.Column('raw', sa.String(length=120), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('phones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phones_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_phones_e164'), ['e164'], unique=False)

    op.create_table('transcripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('phone_raw', sa.String(length=120), nullable=True),
    sa.Column('phone_e164', sa.String(length=20), nullable=True),
    sa.Column('call_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'DONE', 'FAILED', 'NEEDS_REVIEW', name='transcriptstatus', native_enum=False, length=16), server_default='PENDING', nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_sentiment', sa.String(length=16), nullable=True),
    sa.Column('ai_outcome', sa.String(length=64), nullable=True),
    sa.Column('ai_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transcripts_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transcripts_phone_e164'), ['phone_e164'], unique=False)
        batch_op.create_index(batch_op.f('ix_transcripts_status'), ['status'], unique=False)

    op.create_table('calendar_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('transcript_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('all_day', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'AI', name='eventsource', native_enum=False, length=16), server_default='MANUAL', nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=True),
    sa.Column('confirmed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_events_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_starts_at'), ['starts_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_events_starts_at'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_client_id'))

    op.drop_table('calendar_events')
    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcripts_status'))
        batch_op.drop_index(batch_op.f('ix_transcripts_phone_e164'))
        batch_op.drop_index(batch_op.f('ix_transcripts_client_id'))

    op.drop_table('transcripts')
    with op.batch_alter_table('phones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phones_e164'))
        batch_op.drop_index(batch_op.f('ix_phones_client_id'))

    op.drop_table('phones')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index('ix_notes_client_created')

    op.drop_table('notes')
    op.drop_table('client_tags')
    with op.batch_alter_table('campaign_recipients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_recipients_phone_e164'))
        batch_op.drop_index('ix_campaign_recipients_campaign_status')

    op.drop_table('campaign_recipients')
    with op.batch_alter_table('campaign_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_batches_provider_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_batches_campaign_id'))

    op.drop_table('campaign_batches')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_type'))
        batch_op.drop_index('ix_activities_client_occurred')

    op.drop_table('activities')
    op.drop_table('tags')
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_jobs_status'))

    op.drop_table('import_jobs')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_status'))
        batch_op.drop_index(batch_op.f('ix_clients_nip'))
        batch_op.drop_index('ix_clients_name_city')
        batch_op.drop_index(batch_op.f('ix_clients_name'))
        batch_op.drop_index(batch_op.f('ix_clients_email'))
        batch_op.drop_index(batch_op.f('ix_clients_city'))
        batch_op.drop_index(batch_op.f('ix_clients_acronym'))

    op.drop_table('clients')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_status'))

    op.drop_table('campaigns')
    # ### end Alembic commands ###
