"""add next_attempt_at to transcripts

Revision ID: 7ee0d1d10d87
Revises: 0768c92cbf73
Create Date: 2026-08-25 10:46:21.399375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ee0d1d10d87'
down_revision = '0768c92cbf73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        batch_op.drop_column('next_attempt_at')

    # ### end Alembic commands ###
